### ISSUE TITLE
Cannot install on Kibana 6.2.4

### ISSUE THREAD

**Issue by sprijosh** [istresearch/kibana-object-format#26]
I have been trying to install this plugin for Kibana 6.2.4. 

It said it cannot support even I have modified the package from 6.2.3 to 6.2.4

**Comment by molina-rodrigo** [comment]
+1

**Comment by sakthiraam** [comment]
Hi, I'm trying to install in 6.2.4 . Giving me error stating "Error: end of central directory record signature not found".

**Comment by andrewkcarter** [comment]
I'll try and work on it this week.

**Comment by andrewkcarter** [comment]
Here is a build which I tested on Kibana 6.2.4. If you continue to have trouble installing the plugin, please share the steps you are executing and whether you are running Kibana in docker or not so that I may try and reproduce the issue.
https://github.com/istresearch/kibana-object-format/releases/download/v0.1.3/kibana_object_format-0.1.3-kbn_6.2.4.zip

**Comment by andrewkcarter** [comment]
The include is applied first, then exclude. So your exclude of `.*` is your problem.

**Comment by andrewkcarter** [comment]
Just remove the exclude entry entirely for your index.
